#!/usr/bin/env bash
# Interactive WorkOS env setup for local Agent Calendar backend.
# Keys are written only to a local gitignored file (.env.workos.local).
# Do not paste keys into chat or commit them.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT_FILE="$ROOT/.env.workos.local"
EXAMPLE_LOAD="$ROOT/scripts/load-workos-env.example.sh"

echo ""
echo "════════════════════════════════════════════════════"
echo "  Agent Calendar · WorkOS 키 로컬 설정"
echo "════════════════════════════════════════════════════"
echo ""
echo "  · 키는 이 Mac의 로컬 파일에만 저장됩니다."
echo "  · Git에 커밋되지 않습니다 (.env* ignore)."
echo "  · 채팅/PR에 키를 붙여넣지 마세요."
echo ""
echo "  저장 위치: $OUT_FILE"
echo ""

if [[ -f "$OUT_FILE" ]]; then
  echo "  기존 파일이 있습니다. 덮어쓸까요? [y/N]"
  read -r OVERWRITE
  if [[ ! "${OVERWRITE:-}" =~ ^[Yy]$ ]]; then
    echo "  취소했습니다. 기존 파일을 유지합니다."
    echo ""
    echo "  백엔드에 적용하려면:"
    echo "    set -a && source .env.workos.local && set +a && npm run backend:start"
    exit 0
  fi
fi

echo "  WorkOS 대시보드 → API Keys / Configuration 에서 복사하세요."
echo "  https://dashboard.workos.com"
echo ""

read -r -p "  WORKOS_CLIENT_ID (client_...): " CLIENT_ID
if [[ -z "${CLIENT_ID// }" ]]; then
  echo "  오류: Client ID가 비어 있습니다."
  exit 1
fi

# Secret input (no echo)
if [[ -t 0 ]]; then
  read -r -s -p "  WORKOS_API_KEY (sk_...): " API_KEY
  echo ""
else
  echo "  오류: 대화형 터미널이 필요합니다."
  exit 1
fi

if [[ -z "${API_KEY// }" ]]; then
  echo "  오류: API Key가 비어 있습니다."
  exit 1
fi

# Reject common paste mistakes before writing.
if [[ ! "$CLIENT_ID" =~ ^client_[A-Za-z0-9]+$ ]]; then
  echo "  오류: Client ID 형식이 올바르지 않습니다."
  echo "  예: client_01H…  (client_ 로 시작, 공백/라벨 문구 없이)"
  exit 1
fi
if [[ ! "$API_KEY" =~ ^sk_ ]] || [[ ${#API_KEY} -lt 20 ]]; then
  echo "  오류: API Key 형식이 올바르지 않습니다. (길이 ${#API_KEY})"
  echo "  예: sk_test_… 또는 sk_live_…  (붙여넣기 후 Enter, 키는 화면에 안 보입니다)"
  echo "  터미널에서 붙여넣기: Cmd+V 또는 우클릭 → Paste"
  exit 1
fi

umask 077
cat > "$OUT_FILE" <<EOF
# Local only — do not commit. Generated by scripts/setup-workos-env.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export WORKOS_CLIENT_ID=$(printf '%q' "$CLIENT_ID")
export WORKOS_API_KEY=$(printf '%q' "$API_KEY")
EOF
chmod 600 "$OUT_FILE"

echo ""
echo "  저장 완료: $OUT_FILE (mode 600)"
echo ""
echo "  ── 백엔드에 적용 ──"
echo "  set -a && source .env.workos.local && set +a"
echo "  export DATABASE_URL=\"\${DATABASE_URL:-postgres://koyunseo@127.0.0.1:5432/agent_calendar_local}\""
echo "  export PGSSLMODE=disable"
echo "  export PORT=3000"
echo "  npm run backend:start"
echo ""
echo "  ── 로그인 API 확인 ──"
echo "  curl -sS -X POST http://127.0.0.1:3000/api/phase1/auth/desktop/start \\"
echo "    -H 'content-type: application/json' \\"
echo "    -H 'x-agent-calendar-client: desktop-v1' \\"
echo "    -d '{\"screenHint\":\"sign-in\"}'"
echo ""

read -r -p "  지금 백엔드를 이 env로 다시 시작할까요? [y/N] " START_NOW
if [[ "${START_NOW:-}" =~ ^[Yy]$ ]]; then
  # free port 3000
  for p in $(lsof -tiTCP:3000 -sTCP:LISTEN 2>/dev/null || true); do
    kill "$p" 2>/dev/null || true
  done
  sleep 1
  set -a
  # shellcheck disable=SC1091
  source "$OUT_FILE"
  set +a
  export DATABASE_URL="${DATABASE_URL:-postgres://koyunseo@127.0.0.1:5432/agent_calendar_local}"
  export PGSSLMODE=disable
  export PORT=3000
  echo "  백엔드 시작 중 (이 창에서 로그가 이어집니다)…"
  echo ""
  exec npm run backend:start
fi

echo "  준비됐습니다. 키 입력 창을 닫아도 됩니다."
echo ""
